Repository ComNCheck/ComNCheck-FE, pull requests merged in 2025-01, with the labels that each got.

#3 fix : 바텀바 사이즈 수정
  src/app/layout.tsx
  src/components/BottomNavbar.tsx
  src/components/MobileWapper.tsx
Labels: 🚧 리팩토링

#4 fix : 바텀바 수정
  src/app/layout.tsx
  src/components/BottomNavbar.tsx
Labels: 🚧 리팩토링

#5 globalstyle 적용
  src/app/globalStyle.ts
  src/app/layout.tsx
  src/components/BottomNavbar.tsx
  src/components/MobileWapper.tsx
Labels: ⚙ 기능개발

#8 feat : 바텀바 및 모바일뷰 수정
  src/app/layout.tsx
  src/app/styles/ThemeProviderWrapper.tsx
  src/app/styles/globalStyle.ts
  src/app/styles/theme.ts
  src/components/BottomNavbar.tsx
Labels: ✈ 환경세팅, 💎UI 개발

#11 feat : header nav바 제작 및 Pretendard 글꼴 설정 추가
  src/app/layout.tsx
  src/app/my/page.tsx
  src/app/styles/globalStyle.ts
  src/components/HeaderNavbar.tsx
Labels: ✈ 환경세팅, 💎UI 개발

#10 로그인&회원가입 ui완성
  package-lock.json
  package.json
  public/GoogleLogo.svg
  src/app/head.tsx
  src/app/layout.tsx
  src/app/login/first/page.tsx
  src/app/login/page.tsx
  src/app/signup/complete/page.tsx
  src/app/signup/page.tsx
  src/components/button/nextBtn.tsx
Labels: ⚙ 기능개발, 💎UI 개발

#17 feat : my 페이지 홈 제작 완료
  package-lock.json
  package.json
  src/app/my/page.tsx
  src/app/my/question/page.tsx
  src/components/HeaderNavbar.tsx
  src/components/MobileWapper.tsx
Labels: ⚙ 기능개발

#18 Feat : header 위치 수정 및 my 홈 제작중
  package-lock.json
  package.json
  src/app/my/page.tsx
  src/app/my/question/page.tsx
  src/components/HeaderNavbar.tsx
  src/components/MobileWapper.tsx
Labels: ✈ 환경세팅, 💎UI 개발

#21 바텀바 svg 에러 수정
  src/components/BottomNavbar.tsx
Labels: ⚙ 기능개발

#25 fix: 바텀네비바 수정
  src/components/BottomNavbar.tsx
Labels: 🚧 리팩토링, :lady_beetle: 에러수정

#26 회원가입 페이지 기능개발
  package-lock.json
  package.json
  public/example.svg
  src/app/layout.tsx
  src/app/signup/page.tsx
  src/components/button/nextBtn.tsx
  src/components/modal/exampleImg.tsx
Labels: ⚙ 기능개발, 💎UI 개발

#29 feat : my 페이지 내가 쓴글 스크롤 문제 해결
  src/app/my/question/page.tsx
  src/app/my/writingCheck/QuestionCard.tsx
  src/app/my/writingCheck/page.tsx
  src/app/styles/globalStyle.ts
  src/app/styles/theme.ts
  src/components/MobileWapper.tsx
  src/components/SubHeader.tsx
Labels: 💎UI 개발, :lady_beetle: 에러수정

#31 스플래시 화면 생성
  src/app/layout.tsx
  src/app/loading/page.tsx
  src/app/login/first/page.tsx
  src/app/login/page.tsx
  src/app/signup/complete/page.tsx
  src/app/signup/page.tsx
  src/components/button/nextBtn.tsx
Labels: ⚙ 기능개발, :lady_beetle: 에러수정

#34 설정페이지(메인, 개발자에게)
  src/app/layout.tsx
  src/app/setting/page.tsx
  src/app/setting/toDeveloper/page.tsx
  src/components/settingHeader.tsx
  src/components/settingInput.tsx
Labels: ⚙ 기능개발, 💎UI 개발

#36 feat : 답변하기 페이지 제작
  package-lock.json
  package.json
  public/example.svg
  src/app/layout.tsx
  src/app/loading/page.tsx
  src/app/login/first/page.tsx
  src/app/login/page.tsx
  src/app/my/answer/edit/page.tsx
  src/app/my/answer/page.tsx
  src/app/my/answer/write/page.tsx
  src/app/my/components/AddQuestionCard.tsx
  src/app/my/components/CommonContent.tsx
  src/app/my/components/CommonQuestionList.tsx
  src/app/my/components/IsAnswerToggle.tsx
  src/app/my/components/QuestionCard.tsx
  src/app/my/question/page.tsx
  src/app/my/writingCheck/QuestionCard.tsx
  src/app/my/writingCheck/check/page.tsx
  src/app/my/writingCheck/edit/page.tsx
  src/app/my/writingCheck/page.tsx
  src/app/setting/page.tsx
  src/app/setting/toDeveloper/page.tsx
  src/app/signup/complete/page.tsx
  src/app/signup/page.tsx
  src/app/styles/theme.ts
  src/components/BottomNavbar.tsx
  src/components/button/nextBtn.tsx
  src/components/modal/exampleImg.tsx
  src/components/settingHeader.tsx
  src/components/settingInput.tsx
Labels: 💎UI 개발

#38 feat : 세미나실 신청 모달창 제작 완료
  src/app/my/components/modal/seminarAlert.tsx
  src/app/my/page.tsx
Labels: 💎UI 개발

#39 개발자에게 페이지 완성
  package-lock.json
  package.json
  src/app/setting/toDeveloper/page.tsx
  src/components/modal/deleteAlert.tsx
  src/components/modal/toast.tsx
  src/components/settingInput.tsx
Labels: ⚙ 기능개발, 💎UI 개발

#41 학생회 등급신청 페이지
  src/app/setting/applyRating/page.tsx
Labels: ⚙ 기능개발, 💎UI 개발

#42 컴포넌트 분리 및 파일 이동 + 학생회 명단
  src/app/layout.tsx
  src/app/my/answer/edit/page.tsx
  src/app/my/answer/page.tsx
  src/app/my/answer/write/page.tsx
  src/app/my/page.tsx
  src/app/my/question/page.tsx
  src/app/my/writingCheck/check/page.tsx
  src/app/my/writingCheck/edit/page.tsx
  src/app/my/writingCheck/page.tsx
  src/app/setting/applyRating/page.tsx
  src/app/setting/list/page.tsx
  src/app/setting/page.tsx
  src/app/setting/toDeveloper/page.tsx
  src/components/Header/HeaderNavbar.tsx
  src/components/Header/SubHeader.tsx
  src/components/Header/settingHeader.tsx
  src/components/modal/seminarAlert.tsx
  src/components/setting/ContainerBox.tsx
  src/components/setting/TitleContainer.tsx
  src/components/setting/settingInput.tsx
Labels: 💎UI 개발, 🚧 리팩토링

#44 fix : 파일 구조 정리 및 컴포넌트 분리
  src/app/my/answer/edit/page.tsx
  src/app/my/answer/page.tsx
  src/app/my/answer/write/page.tsx
  src/app/my/modifyRole/page.tsx
  src/app/my/myComponents/AddQuestionCard.tsx
  src/app/my/myComponents/CommonContent.tsx
  src/app/my/myComponents/CommonQuestionList.tsx
  src/app/my/myComponents/CommonRoleList.tsx
  src/app/my/myComponents/IsAnswerToggle.tsx
  src/app/my/myComponents/QuestionCard.tsx
  src/app/my/myComponents/RoleCard.tsx
  src/app/my/page.tsx
  src/app/my/question/page.tsx
  src/app/my/writingCheck/check/page.tsx
  src/app/my/writingCheck/edit/page.tsx
  src/app/my/writingCheck/page.tsx
  src/components/Container.tsx
  src/components/Header/HeaderNavbar.tsx
  src/components/MobileWapper.tsx
  src/components/button/SubmitButton.tsx
  src/components/container/ContainerWrapper.tsx
  src/components/container/ContentBoxSmall.tsx
  src/components/container/FormWrapper.tsx
  src/components/setting/TitleContainer.tsx
Labels: :lady_beetle: 에러수정

#46 이수체계도 + 설정페이지 완료
  src/app/setting/applyRating/page.tsx
  src/app/setting/curriculum/curriculumData.js
  src/app/setting/curriculum/page.tsx
  src/app/setting/toDeveloper/page.tsx
  src/app/styles/theme.ts
  src/components/Header/settingHeader.tsx
  src/components/setting/TitleContainer.tsx
Labels: ⚙ 기능개발, 💎UI 개발, 🚧 리팩토링

#50 feat : MY 페이지 제작 완료
  src/app/faq/check/page.tsx
  src/app/faq/page.tsx
  src/app/my/modifyRole/page.tsx
  src/app/my/myComponents/CommonRoleList.tsx
  src/app/my/myComponents/RoleCard.tsx
  src/app/my/page.tsx
  src/app/setting/applyRating/page.tsx
  src/app/setting/curriculum/curriculumData.js
  src/app/setting/curriculum/page.tsx
  src/app/setting/toDeveloper/page.tsx
  src/app/styles/theme.ts
  src/components/Header/settingHeader.tsx
  src/components/modal/RoleCheckModal.tsx
  src/components/setting/TitleContainer.tsx
Labels: 💎UI 개발

#49 feat : FAQ 페이지 제작 완료
  src/app/faq/check/page.tsx
  src/app/faq/page.tsx
  src/app/my/page.tsx
Labels: ⚙ 기능개발, 💎UI 개발

#53 구글 로그인 서버연결 테스트
  package-lock.json
  package.json
  src/app/login/page.tsx
  src/app/signup/page.tsx
Labels: ⚙ 기능개발, 🎛 테스트
