Repository ComNCheck/ComNCheck-FE, pull requests merged in 2025-02, with the labels that each got.

#54 로그인 서버 연결
  src/app/login/first/page.tsx
  src/app/signup/page.tsx
Labels: ⚙ 기능개발, 🎛 테스트

#61 [FEAT] 공지 페이지 ui 제작 완료
  public/bannerBackground.png
  src/app/my/page.tsx
  src/app/notice/Component/EventBtn.tsx
  src/app/notice/Component/NoticeCard.tsx
  src/app/notice/Component/NoticeCommonCard.tsx
  src/app/notice/college/page.tsx
  src/app/notice/employment/page.tsx
  src/app/notice/event/detail/page.tsx
  src/app/notice/event/enroll/page.tsx
  src/app/notice/event/page.tsx
  src/app/notice/page.tsx
  src/components/Header/SlideHeader.tsx
  src/components/Header/SubHeader.tsx
  src/components/container/ContainerWrapper.tsx
  src/components/container/FormWrapper.tsx
Labels: 💎UI 개발

#66 api 연동 수정 사항(test중)
  src/apis/developerQuestion.ts
  src/apis/roleChange.ts
  src/app/login/first/page.tsx
  src/app/setting/applyRating/page.tsx
  src/app/setting/list/page.tsx
  src/app/setting/toDeveloper/page.tsx
  src/app/signup/page.tsx
  src/components/setting/settingInput.tsx
Labels: 🎛 테스트, :lady_beetle: 에러수정, 📬api 연결

#70 feat : MY - 질문하기 post, get api 연동 수정
  src/apis/question.ts
  src/app/faq/page.tsx
  src/app/my/page.tsx
  src/app/notice/page.tsx
Labels: 📬api 연결

#71 Fix/setting input
  public/logo.svg
  src/apis/developerQuestion.ts
  src/apis/developerQuestion.type.ts
  src/app/setting/toDeveloper/page.tsx
  src/app/signup/page.tsx
  src/components/setting/settingInput.tsx
Labels: :lady_beetle: 에러수정

#72 Feat : api 연동
  src/apis/answer.ts
  src/apis/question.ts
  src/apis/question.type.ts
  src/apis/roleChange.ts
  src/apis/roleChange.type.ts
  src/app/my/answer/edit/page.tsx
  src/app/my/answer/page.tsx
  src/app/my/answer/write/page.tsx
  src/app/my/modifyRole/page.tsx
  src/app/my/myComponents/CommonRoleList.tsx
  src/app/my/myComponents/IsAnswerToggle.tsx
  src/app/my/myComponents/QuestionCard.tsx
  src/app/my/myComponents/RoleCard.tsx
  src/app/my/writingCheck/check/page.tsx
  src/app/my/writingCheck/page.tsx
  src/components/modal/RoleCheckModal.tsx
  src/components/modal/seminarAlert.tsx
Labels: 📬api 연결

#74 feat: 로그인 상태에 따른 페이지 리다이렉팅
  src/apis/developerQuestion.ts
  src/app/layout.tsx
  src/app/page.tsx
Labels: ⚙ 기능개발

#76 hotfix: 빌드에러 수정중
  src/app/faq/check/page.tsx
  src/app/my/modifyRole/page.tsx
  src/app/my/myComponents/RoleCard.tsx
  src/app/notice/Component/NoticeCommonCard.tsx
  src/app/notice/college/page.tsx
  src/app/notice/employment/page.tsx
  src/app/notice/event/detail/page.tsx
  src/app/notice/event/page.tsx
  src/app/setting/curriculum/page.tsx
  src/app/setting/list/page.tsx
  src/components/BottomNavbar.tsx
  src/components/modal/RoleCheckModal.tsx
Labels: :lady_beetle: 에러수정

#79 Feat/Fix : FAQ 페이지 api 연동, 및 빌드 오류 수정
  src/apis/question.ts
  src/apis/question.type.ts
  src/app/faq/check/page.tsx
  src/app/faq/page.tsx
  src/app/login/page.tsx
  src/app/my/myComponents/FAQQuestionList.tsx
  src/app/my/writingCheck/check/page.tsx
  src/components/BottomNavbar.tsx
  src/components/modal/RoleCheckModal.tsx
Labels: :lady_beetle: 에러수정, 📬api 연결

#80 feat&hotfix: 공지 api연결
  public/privacy-policy.html
  public/terms-of-service.html
  src/apis/notice.ts
  src/apis/notice.type.ts
  src/app/notice/Component/NoticeCard.tsx
  src/app/notice/Component/NoticeCommonCard.tsx
  src/app/notice/college/page.tsx
  src/app/notice/employment/page.tsx
  src/app/notice/event/enroll/page.tsx
  src/app/notice/event/page.tsx
  src/app/notice/page.tsx
Labels: :lady_beetle: 에러수정, 📬api 연결

#81 알림 토글 api연동
  src/apis/alarm.ts
  src/apis/notice.ts
  src/apis/notice.type.ts
  src/app/notice/page.tsx
  src/components/button/toggleBtn.tsx
Labels: 💎UI 개발, 📬api 연결

#83 버튼 visible 및 사진 에러 수정
  src/app/notice/Component/EventBtn.tsx
  src/app/notice/event/detail/page.tsx
  src/app/notice/event/enroll/page.tsx
  src/app/signup/page.tsx
Labels: :lady_beetle: 에러수정

#86 로그아웃 api추가
  src/apis/developerQuestion.ts
  src/apis/member.ts
  src/app/my/page.tsx
  src/app/seminarRoom/page.tsx
  src/app/setting/page.tsx
  src/app/signup/page.tsx
  src/components/Header/settingHeader.tsx
  src/components/loading/LoadingSpinner.tsx
Labels: ⚙ 기능개발, 📬api 연결

#87 배포를 위한 리팩토링
  src/apis/member.ts
  src/apis/member.type.ts
  src/app/login/first/page.tsx
  src/components/Header/settingHeader.tsx
Labels: 🚧 리팩토링

#88 hotfix:빌드에러수정
  src/app/login/first/page.tsx
Labels: :lady_beetle: 에러수정

#89 hotfix:첫 로그인화면 수정
  src/apis/member.ts
  src/app/login/first/page.tsx
Labels: :lady_beetle: 에러수정

#91 test코드(원래 코드로 돌림)
  src/app/login/first/page.tsx
Labels: 🎛 테스트

#93 hotfix: 공지페이지에서 사용자 정보 불러오기
  src/app/notice/page.tsx
Labels: :lady_beetle: 에러수정

#94 feat : [공지]api 수정
  src/app/notice/page.tsx
Labels: 📬api 연결

#95 fix: 빌드에러 및 타입에러
  src/app/notice/event/page.tsx
  src/app/notice/page.tsx
  src/components/Header/SlideHeader.tsx
Labels: :lady_beetle: 에러수정

#96 feat:학생회 등급신청 시 로컬에서 값 불러서채우기
  src/app/setting/applyRating/page.tsx
Labels: ⚙ 기능개발

#97 fix: 공지 페이지 일부 수정(행사입력, 알림기능)
  src/apis/alarm.ts
  src/app/notice/college/page.tsx
  src/app/notice/employment/page.tsx
  src/app/notice/event/enroll/page.tsx
  src/app/notice/event/page.tsx
  src/components/button/toggleBtn.tsx
  src/components/notice/inputForm.tsx
Labels: ⚙ 기능개발, :lady_beetle: 에러수정

#107 요청사항 수정
  next.config.ts
  src/apis/instance.ts
  src/app/notice/event/detail/page.tsx
  src/components/setting/settingInput.tsx
Labels: ⚙ 기능개발, ✈ 환경세팅

#109 feat: 과행사 글 수정하기 api
  src/apis/notice.ts
  src/app/faq/check/page.tsx
  src/app/my/answer/edit/page.tsx
  src/app/my/answer/write/page.tsx
  src/app/notice/event/detail/page.tsx
  src/app/notice/event/modify/page.tsx
  src/components/button/toggleBtn.tsx
Labels: 📬api 연결

#111 hotfix&test: 배포 테스트
  src/apis/instance.ts
Labels: :lady_beetle: 에러수정
