Repository ComNCheck/ComNCheck-FE, pull requests merged in 2025-03, with the labels that each got.

#117 fix : 과행사 공지 확인하기에서 과회장/학생회 등급일때만 밀어서 삭제하기 기능 추가
  src/app/notice/Component/NoticeCard.tsx
  src/app/notice/event/page.tsx
  src/app/notice/page.tsx
Labels: ⚙ 기능개발

#120 setting : 구글 애널리틱스 기능 추가
  src/app/layout.tsx
  src/lib/GoogleAnalytics.tsx
Labels: ✈ 환경세팅

#122 [QA] 과행사 시간 신청 및 ui 깨지는 문제 해결
  src/app/my/myComponents/FAQQuestionList.tsx
  src/app/notice/event/enroll/page.tsx
  src/app/notice/event/modify/page.tsx
  src/components/Header/HeaderNavbar.tsx
  src/components/container/ContainerWrapper.tsx
Labels: :lady_beetle: 에러수정

#124 [QA] 문제사항 해결(ui부분)
  src/app/my/myComponents/FAQQuestionList.tsx
  src/components/Header/HeaderNavbar.tsx
  src/components/container/ContainerWrapper.tsx
  src/components/container/FormWrapper.tsx
  src/components/setting/TitleContainer.tsx
Labels: :lady_beetle: 에러수정

#127 fix: 넘치는 컴포넌트 스크롤되도록 수정
  src/app/faq/check/page.tsx
  src/app/faq/page.tsx
  src/app/login/page.tsx
  src/app/my/answer/edit/page.tsx
  src/app/my/answer/page.tsx
  src/app/my/answer/write/page.tsx
  src/components/BottomNavbar.tsx
Labels: ⚙ 기능개발, :lady_beetle: 에러수정

#130 [QA&fix]과행사 공지글에서 사진 여러개 뜨도록 수정
  src/app/notice/event/detail/page.tsx
  src/app/notice/page.tsx
  src/app/setting/applyRating/page.tsx
Labels: ⚙ 기능개발, 💎UI 개발

#142 fix : 공지 ui 수정
  public/bannerBackground.png
  src/app/notice/page.tsx
  src/components/Header/SlideHeader.tsx
Labels: 💎UI 개발
